spacetelescope/drizzle

.travis.yml, README.rst, docs/conf.py, drizzle/util.py, setup.py
=> Update astropy-helpers -> 1.2.x; Fix build for Python 3.5.2

drizzle/setup_package.py, drizzle/src/tests/pandokia_fct.h, drizzle/src/tests/utest_cdrizzle.c
ref: https://github.com/spacetelescope/jwst/issues/3132
=> Allow win32 to compile

.travis.yml, drizzle/__init__.py, drizzle/_astropy_init.py, drizzle/calc_pixmap.py, drizzle/conftest.py, drizzle/doblot.py, drizzle/tests/test_drizzle.py, drizzle/tests/test_pixmap.py, drizzle/util.py, setup.cfg
- Fix the .travis.yml file so it actually parses
- Update the matrix in Travis CI to use more recent versions of `numpy`
- Fix setup.cfg to use `[tool:pytest]`
- Point the `flake8` test to the actual code so that it is doing something
- Fix all the PEP8 issues
- Fix astropy test helpers in conftest.py
=> Fix CI for this package

.gitignore, .travis.yml, drizzle/tests/setup_package.py, setup.cfg, setup.py
Knocks off a few hundred MBs
Fixes #42.
Closes #46.
=> Stop packaging the test data

.github/workflows/drizzle_ci.yml
=> Adding github actions for continuous integration.

.coveragerc, .github/workflows/drizzle_ci.yml, setup.cfg
Adding code coverage to github actions.
=> Add coverage to CI

drizzle/drizzle.py, drizzle/tests/test_drizzle.py, setup.cfg
=> Fix context plane shape bug

drizzle/tests/test_drizzle.py
This PR improves the unit test from https://github.com/spacetelescope/drizzle/pull/79
=> Improve unit test for 0-weight bug

docs/index.rst
=> remove mention of affiliation with Astropy

drizzle/tests/test_drizzle.py, pyproject.toml, setup.cfg, tox.ini
use `ruff` in tox env and apply fixes from `ruff --fix drizzle/`
=> use `ruff` instead of `flake8`

.github/workflows/ci.yml, setup.py, tox.ini
=> refactor toxenvs and use OpenAstronomy workflows

src/cdrizzleutil.h
Unit tests are failing on Windows because the file `/tmp/drizzle.log` cannot be created at that location. This PR fixes that.
=> Fix unit tests' failure on Windows

.readthedocs.yaml, docs/conf.py, docs/drizzle/api.rst, docs/rtd-pip-requirements, docs/rtd_environment.yaml, drizzle/doblot.py, pyproject.toml
Another attempt based off of: https://github.com/spacetelescope/drizzle/pull/111
@zacharyburnett @nden @mcara  Would you check if this correctly built all the docs?
=> Bjg drizzle rtd

drizzle/tests/test_overlap_calc.py
Follow-up to #137, this PR adds a unit test.
=> Add unit test for pixel inversion with small image

CHANGES.rst
=> Prepare for release 1.15.1

.github/workflows/build.yml, docs/conf.py, pyproject.toml, setup.py, tox.ini
resolves [SCSB-149](https://jira.stsci.edu/browse/SCSB-149)
=> ensure extension modules are present in built wheel

pyproject.toml
This should fix the build failures.
=> require < python 3.13

.github/workflows/ci.yml
[SCSB-195](https://jira.stsci.edu/browse/SCSB-195)
=> test with latest supported Python version

README.rst
=> Update docs references

CHANGES.rst, drizzle/resample.py, drizzle/tests/test_resample.py
=> Fix a crash when initializing Drizzle with disabled context array

setup.py, src/cdrizzleapi.c, src/cdrizzlemap.c, src/cdrizzleutil.c, src/tests/pandokia_fct.h, src/tests/utest_cdrizzle.c
~I think this fixes the last compiler warning (at least on Mac).~
This PR fixes some compiler warnings.
=> add extra compile flags and fix compiler warning

.clang-format, drizzle/tests/test_resample.py, src/cdrizzleapi.c, src/cdrizzleblot.c, src/cdrizzlebox.c, src/cdrizzlemap.c, src/cdrizzlemap.h, src/cdrizzleutil.h
Add braces around single-line statements after control statements `if`, `else`, `while`, etc.
=> Format: insert braces around unguarded statements
