spacetelescope/drizzle

- drizzle/tests/test_drizzle.py
- drizzle/tests/test_file_io.py
This allows to run the tests when installed, and it also avoids pollution of the test data subdir during a normal test.
By default, the output dir is created in `/tmp` and removed after the test. This can be overwritten with the environment variable `DRIZZLE_TEST_OUTPUT_DIR`, which also inhibits the automatical removal.
This fixes #8.
> Separate the output dir for tests from the data dir

- drizzle/src/cdrizzleapi.c
- drizzle/src/cdrizzlemap.c
- drizzle/src/cdrizzleutil.h
- drizzle/src/tests/drizzletest.h
- drizzle/src/tests/utest_cdrizzle.c
This is done by defining NPY_NO_DEPRECATED_API to version 1.10, and
change the definition of the PyArray_* data types to NPY_*.
> Remove numpy deprecation warning

- .travis.yml
- drizzle/src/cdrizzlemap.c
- drizzle/src/cdrizzlemap.h
- drizzle/src/tests/utest_cdrizzle.c
Some instruments do not define a coordinate transformation across the
entire image. In these cases the pixmap which is passed to drizzle
contains NaN values in some pixels. Usually these pixels are around
the edge of the image. Since the drizzle code was not written to
handle the case of NaN values, it needed to be modified.
Two modifications were made. Now the code only drizzles image areas
where the pixmap contains defined values. The change treats areas in
the input image where pixmap contains NaNs as if they do not overlap
the output image. This change is in a new function, shrink_segment,
which is called by clip_bounds.
Also, the bilinear interpolation code which handle the coordinate
transformation at fractional pixel values excludes pixels with NaN
values. This typically will …
> Correctly handle pixmaps containing NaN values

- drizzle/src/cdrizzlemap.c
- drizzle/src/tests/utest_cdrizzle.c
The new code restores an older algorithm that searches each dimension separately. This is to ensure that the bounds returned by differ on the dimension that is being interpolated over.
> Revise map_bounds point search algorithm

- drizzle/src/cdrizzlemap.c
- drizzle/src/tests/utest_cdrizzle.c
- setup.py
The function shrink_segment in cdrizzlemap.c reduces the segment length to exclude NaN values on either end of the segment. The old version did not check to see if the segment lies entirely inside the bounds of the image, and sometimes it is called with segments like this. I added checks so that the search for NaN values starts on the image and not outside it.
> Add check to input of shrinks_segment to prevent checks outside of array

- .travis.yml
- drizzle/src/cdrizzleapi.c
- drizzle/src/cdrizzleblot.c
- drizzle/src/cdrizzlebox.c
- drizzle/src/cdrizzlemap.c
- drizzle/src/cdrizzlemap.h
- drizzle/src/cdrizzleutil.h
- drizzle/src/tests/utest_cdrizzle.c
- setup.py
Drizzle computes the overlap between each line of the input image and the output image. Part of the computation is shrink_segment, which reduces the length of the input image line if there are NaN values along the edge of the image. That code mistakenly assumed that the size of the input image and pixel map were the same, leading to the out of bounds error when the pixel map was larger. The code in shrink_segment has been modified to intialize the line length from the input image and not the pixel map.
Some logging code has been added to cdrizzleutil.h and various functions to make catching errors easier in the future. The code is controlled by a C macro, LOGGING, and is usually turned off. There is a new global variable, driz_log_handle, defined in cdrizzleapi, initiallized to NULL.
> Fix out of bounds array error caused by shrink_segment

- drizzle/src/cdrizzleapi.c
- drizzle/src/cdrizzlemap.c
- drizzle/src/cdrizzlemap.h
- drizzle/src/tests/utest_cdrizzle.c
- setup.py
Before drizzling input pixels onto the output image, drizzle must first determine what part of each input line overlaps the output image. And since lines typically have invalid values at their edges,
we would rather deal with the valid portion of the input line than the whole line. Shrink_segment walks inward from the edges of the line to find the first valid value, that is, a value that is not NaN. The logic of the code was previously badly wrong, leading to a segmentation error when the size of the input and output images differed. The revised code fixes the logic error and changes the
parameter list of shrink_segment.
> Fix logic of shrink_segment

- .travis.yml
- drizzle/src/cdrizzleapi.c
- drizzle/src/cdrizzleblot.c
- drizzle/src/cdrizzlebox.c
- drizzle/src/cdrizzlemap.c
- drizzle/src/cdrizzlemap.h
- drizzle/src/cdrizzleutil.h
- drizzle/src/tests/utest_cdrizzle.c
- setup.py
The drizzle code expects that the dimensions of the input image and pixmap file are the same. The blotting code expects the dimensions of the output image and pixmap file are the same. Prior to this change, the C code would throw a segmentation violation if the pixmap did not meet this condition. This change adds a check and throws an explicit error if the condition is not met. If your pixmap is larger than the input/output image, it can be trimmmed to match the dimensions. If it is smaller, resize it to have the correct dimensions and fill the undefined pixels with NaN and the function shrink_segment will see that only the corresponding section of the input image is used in the
drizzle. Some diagnostic prints used in debugging C errors are also modified in this change. They are turned …
> Add pixmap dimension check to drizzle

- drizzle/src/cdrizzlebox.c
- drizzle/src/cdrizzlemap.c
- drizzle/src/cdrizzlemap.h
- drizzle/src/cdrizzleutil.h
- drizzle/src/tests/utest_cdrizzle.c
- setup.py
A recent change in the pipeline code has resulted in the pixmap only being partially populated with values mapping from the input to output images. The remainder of the pixmap is populated with NaNs. When mapping a point between the input and output image, one must first find a bound, a set of four pixels that allows one to do an interpolation or extrapolation in two dimensions. The bound does not need to be the immediate neighbors of the interpolated point, but does need to be in the bordering rows and columns of the point. For this reason the interpolation fails if a bordering row or column is entirely NaNs. This typically happens when spectra are being drizzled, the defined area of the pixmap is only a subregion of the detector image.
To handle this common situation, the drizzle code …
> Have proper bounds when interpolating in pixmap or fail gracefully

- .travis.yml
- setup.py
The C header files need to be included when building the source distribution.  I also bumped the version number, in preparation for a PyPi release.
> Add header files to package_info

- .travis.yml
- drizzle/dodrizzle.py
- drizzle/drizzle.py
- drizzle/src/cdrizzleapi.c
- drizzle/tests/test_file_io.py
- setup.py
The drizzle user has the option of setting unwritten pixels in the output image to a fill value rather than the default value of zero. This value is set by the drizzle parameter fillstr. If this parameter is "NaN" or "nan" the fill value in the output image will be "Not a Number."
> Support NaN as a fill value

- drizzle/calc_pixmap.py
- drizzle/doblot.py
- drizzle/drizzle.py
- drizzle/tests/test_pixmap.py
This is a propagation of https://github.com/astropy/astropy/pull/7973
This would tether Drizzle to Astropy >=3.1.
Signed-off-by: James Noss <jnoss@stsci.edu>
> Remove use of deprecated astropy.WCS _naxis1 & _naxis2

- .gitignore
- drizzle/tests/test_cdrizzle.py
- drizzle/tests/test_drizzle.py
- drizzle/tests/test_file_io.py
- drizzle/tests/test_pixmap.py
- drizzle/util.py
- setup.cfg
Fixes the following deprecation of `np.matrix`:
```
drizzle/drizzle/util.py:242: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
pc = np.matrix(the_wcs.wcs.get_pc())
```
> Remove use of deprecated np.matrix

- pyproject.toml
- setup.cfg
- setup.py
Instead of using the latest version of `numpy` as the build dependency, use the oldest compatible one via the meta package
https://github.com/scipy/oldest-supported-numpy
so that the compiled code can be used with any new version of `numpy` in the runtime environment.
This should resolve the issue discussed in https://github.com/spacetelescope/jwst/issues/5744
For more detail, see https://github.com/pypa/pip/issues/9542
> Use oldest-supported-numpy in pyproject.toml

- CHANGELOG.rst
- src/cdrizzleblot.c
Fixes an issue with bilinear interpolator used in the blot function due to which code was trying to access elements outside of the data array resulting in segfault.
This effectively fixes https://github.com/spacetelescope/jwst/issues/6116
This PR also adds a changelog file to this repository though it starts with current issue.
> Fix memory corruption in the linear blot algorithm

- CHANGES.rst
- drizzle/tests/test_drizzle.py
- src/cdrizzlebox.c
This PR fixes a bug in the C code of the core drizzle algorithm due to which flux from the input image could be dropped onto the output (resampled) image even though those input pixels have zero weights.
The same bug is present in the C code in the `drizzlepac`.
Fixes https://github.com/spacetelescope/jwst/issues/6167
> Fix incorrect drizzling when inwht is 0

- CHANGES.rst
- src/cdrizzlemap.c
Closes #82
Resolves https://jira.stsci.edu/browse/JP-2702
This is an alternative PR to #82 and fixes the interpolation algorithm used by the square kernel. First, the interpolation itself is now bilinear. Second, the algorithm for finding vertices of the interpolation rectangle (`interpolation_bounds()`) was replaced with a simplified version `interpolation_starting_point()` that does not have the
> Bounce around the starting point until we find four valid points on the line
logic. That is, if one of the vertices has an `NaN` value then interpolation result will also be an `NaN`. I do not think this should cause problems but it should be checked with images that have WCS with bounding boxes and whose WCS produces NaNs outside of bounding boxes.
My initial testing shows that this PR solves …
> JP-2702: Fix image shifts with square kernel

- CHANGES.rst
- src/cdrizzlemap.c
This PR fixes a bug in how pixel mapping and interpolation functions report cases of invalid coordinate values. This could lead to resampled images having all zeros. The issue was first reported by @hbushouse from testing of the `jwst` pipeline.
> Fix a bug in how pixel mapping reports invalid coordinates

- CHANGES.rst
- src/cdrizzlemap.c
It was reported (help desk ticket INC0186717) that under some circumstances, some parts of input images may be missing in the resampled output images. This occurs when a vertex of the input image is outside of the resampled image. I traced this to be a bug in how algorithm identifies which lines in the input images are completely outside of the output image.
The image below illustrates the issue. Notice missing data in the top-right corner:
This PR fixes the issue.
> Fix incorrect identification of lines to be skipped

- .readthedocs.yaml
Currently, documentation is hosted on GitHub Pages at https://spacetelescope.github.io/drizzle/
This PR adds a ReadTheDocs configuration to build on RTD. Once the `.readthedocs.yaml` file is put in the main branch we should be able to create a RTD instance on https://readthedocs.org
> add ReadTheDocs configuration

- src/tests/fct.h
- src/tests/utest_cdrizzle.c
Unit tests have been disabled for quite some time and https://github.com/spacetelescope/drizzle/pull/85 made them fail once tests have been restarted. This PR updates unit tests to pass again given changes in to the pixel mapping code implemented in https://github.com/spacetelescope/drizzle/pull/85
> Update unit tests

- tox.ini
Resolves [SCSB-69](https://jira.stsci.edu/browse/SCSB-69)
uses the `pre` wheels of `astropy` and `numpy` in the `devdeps` tests
> test against pre-built binaries of `astropy` and `numpy`

- tox.ini
This PR addresses @WilliamJamieson's comments in https://github.com/spacetelescope/romancal/pull/695#discussion_r1189078751; the change to the Astropy dev spec in #100 didn't actually accomplish anything, and `numpy` wheels are hosted at a different index URL
> revert astropy prerelease wheel spec and use nightly Scipy wheel index

- src/tests/utest_cdrizzle.c
#83 fixed a bug in the interpolation algorithm but it did not update unit tests. This PR fixes those unit tests.
Closes #88
> Fix failing tests after interpolation bug fix

- .github/workflows/ci.yml
> [CI] add Windows job and rename `toxenv`s to include Python version

- pyproject.toml
closes #106 
Note: entries in `tool.setuptools` DO use hyphens, not underscores (https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)
> use underscores in `upload_docs` config

- docs/conf.py
- pyproject.toml
#93 broke code in `docs/conf.py` that was relying on metadata in `setup.cfg`. This PR fixes this specific error.
> Fix latest doc build failure: missing setup.cfg

- .gitignore
- CHANGES.rst
- drizzle/tests/test_cdrizzle.py
- drizzle/tests/test_overlap_calc.py
- src/cdrizzleapi.c
- src/cdrizzlebox.c
- src/cdrizzlemap.c
- src/cdrizzlemap.h
- src/cdrizzleutil.h
- src/tests/utest_cdrizzle.c
This is the second attempt to fix the issue described in https://github.com/spacetelescope/drizzle/pull/89. That fix was working only sometimes. This PR is a complete re-design of how `drizzle` computes image overlaps and scan lines.
Resolves #41
Resolves #63 
Fixes #87
Regression tests:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/841
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/872 (for 92b4deb)
> Fix incorrect overlap computations

- CHANGES.rst
- src/cdrizzleapi.c
Fixes test failures on big endian architectures. The code in this PR is based on *analysis* of the code and it has not been tested on a big endian machine since I do not have access to one, at least not at this moment.
Closes #115 
@olebole Would it be possible for you to test this from this branch or would you prefer me making a release.
CC: @hbushouse @nden
> Fix test failures on big endian architectures

- CHANGES.rst
- src/cdrizzleutil.h
Disables logging by default and fixes issues with logging that were causing #118. In general, logging should be redesigned completely in the `drizzle` and this will be added to the TODO list.
NOTE: logging was disabled previously but was left enabled inadvertently during the work on polygon intersections.
Fixes #118
> Fix segfault on some systems

- .github/workflows/ci.yml
- README.rst
resolves [SCSB-121](https://jira.stsci.edu/browse/SCSB-121)
preparation for branch rename
> [SCSB-121] rename `master` -> `main`

- CHANGES.rst
- src/cdrizzlemap.c
Fixes a bug in the pixel coordinate inversion routine (from output frame to input frame). In part `fixes` #132 (first example).
> Fix a bug in pixel inversion routine

- CHANGES.rst
- drizzle/tests/test_drizzle.py
- src/cdrizzleapi.c
This PR adds unit tests that verify that "square", "turbo", and "point" kernels do conserve flux.
It also modifies the warning type for the "non flux conserving" kernels from ``DeprecationWarning`` to ``Warning``.
> Change warning type for some kernels. Add unit tests for flux conservation

- drizzle/tests/test_overlap_calc.py
Relaxes the accuracy of identical polygon testing as `test_intersection_case01` seems to fail with Python 3.12 on Mac OSX.
> Fix identical polygon test accuracy for unit tests

- .github/workflows/ci.yml
- README.rst
- pyproject.toml
resolves [SCSB-145](https://jira.stsci.edu/browse/SCSB-145)
propagate Astropy's deprecation of Python 3.9 to downstream packages
> [!NOTE]
> this PR was generated automatically by ``batchpr`` :robot:
> [SCSB-145] require Python 3.10

- src/cdrizzleapi.c
The return type of the init function is `PyMODINIT_FUNC`, not `PyMODINIT_FUNC *`.
This was found by an error raised when built with gcc-14, see [Debian#1075414](https://bugs.debian.org/1075414).
> Fix return type of PyInit_cdrizzle

- CHANGES.rst
- drizzle/tests/test_drizzle.py
- src/cdrizzleapi.c
This PR allows `context` to be `None` for `tdriz` (to prevent the need for a context array).
One place where this would be useful is within the jwst and romancal pipelines where drizzle is used to generate intermediate products for outlier detection. These operations can involve large arrays and using `context=None` (and not generating a large context array) can result in memory savings.
> allow `context` to be `None`

- .github/workflows/ci.yml
- pyproject.toml
- tox.ini
This PR:
- adds python 3.13 testing to the CI: https://github.com/spacetelescope/drizzle/actions/runs/10473588949/job/29005811343?pr=156
- allows python 3.13 in pyproject.toml
- re-enables to previously disabled tox devdeps test https://github.com/spacetelescope/drizzle/actions/runs/10473588949/job/29005812771?pr=156
I added the devdeps change only because I saw the comment:
https://github.com/spacetelescope/drizzle/blob/f8ea30dc5b1eda828aa1e4191c9d9205f01551ae/.github/workflows/ci.yml#L35-L36
Since numpy 2.0 is out I figured I'd see if it works again (which it did). Let me know if it's preferable to have this change in a different PR.
> allow python 3.13

- .clang-format
- src/cdrizzleapi.c
- src/cdrizzleblot.c
- src/cdrizzleblot.h
- src/cdrizzlebox.c
- src/cdrizzlebox.h
- src/cdrizzlemap.h
- src/cdrizzleutil.c
- src/cdrizzleutil.h
- src/driz_portability.h
- src/tests/.clang-format
- src/tests/drizzletest.h
- src/tests/utest_cdrizzle.c
Apply uniform style to C code similar to PEP8 rules for Python code. This uses modified Google style. "external" FCT headers have been moved to a separate folder in order to be excluded from style formatting. This style tries to follow https://peps.python.org/pep-0007/ vague "guide" as much as possible.
This is 2nd attempt at this after several larger changes of the C code in recent commit. It was easier to open a new PR in favor of rebasing #113 and solving numerous merge conflicts.
Closes #113
> Reformat C code using clang-format

- .github/workflows/ci.yml
this should fix the codecov upload not working for `main` (it works without a token on PRs)
> add codecov token to uploader step

- drizzle/resample.py
- pyproject.toml
- tox.ini
`astropy` is needed only for testing.
> Cleanup dependencies

- drizzle/tests/helpers.py
- drizzle/tests/test_utils.py
- drizzle/utils.py
- pyproject.toml
Adds unit tests that utilize `gwcs` in addition to FITS WCS.
> Add unit tests that use gwcs. Fix how the bounding box is handled.

- .github/workflows/ci.yml
- CHANGES.rst
- drizzle/tests/test_utils.py
- drizzle/utils.py
Prepare for https://github.com/spacetelescope/gwcs/pull/498 by disabling bounding box in `calc_pixmap`.
> Disable bounding box in calc_pixmap

- drizzle/tests/test_resample.py
- drizzle/utils.py
Improves unit test added in #177 by using random weights for input image pixels compared to constant weight set to one in the original test.
> Use random weights in the unit test for multi-src flux conserve

- CHANGES.rst
- drizzle/resample.py
- drizzle/tests/test_resample.py
- drizzle/tests/test_utils.py
Fixes #169
Regression tests:
JWST: https://github.com/spacetelescope/RegressionTests/actions/runs/13406783281
Roman: https://github.com/spacetelescope/RegressionTests/actions/runs/13406785388
> Fix a bug in Drizzle when out_img=None and fillval is INDEF

- .github/workflows/ci.yml
- setup.py
Currently `drizzle` build on CI is failing with:
```
LINK : fatal error LNK1104: cannot open file 'python313t.lib'
```
apparently due to https://github.com/python/cpython/issues/135151
This PR implements the solution is to ignore 1.13.4 as in https://github.com/spacetelescope/stcal/pull/351
> Fix failing tests due to Python 3.13.4 win32 GIL issues

- .coveragerc
- CHANGES.rst
- drizzle/resample.py
- drizzle/tests/test_resample.py
- drizzle/tests/test_utils.py
- src/cdrizzleapi.c
- src/cdrizzlebox.c
- src/cdrizzleutil.c
- src/cdrizzleutil.h
- src/tests/utest_cdrizzle.c
This PR adds support for resampling and adding resampled (error, variance) images with squared weights. This is to facilitate standard error propagation.
> Add support for co-adding with squared weights

- src/cdrizzleapi.c
- src/cdrizzleblot.c
- src/cdrizzlemap.c
- src/cdrizzleutil.h
This PR removes a couple of unused variables and fixes compiler warnings related to function type conversion.
> Remove unused variables and fix function type conversion warnings

- src/cdrizzlebox.c
- src/cdrizzleutil.c
- src/cdrizzleutil.h
This PR adds a warning about `pixfrac` being ignored when resampling with "lanczos" kernel when `pixfrac != 1`. Also fixes some comments in the code.
> Add a warning about ignoring pixfrac with lanczos kernel
